# Generated by Django 4.1.2 on 2022-10-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('situation', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('level_needy', models.CharField(max_length=50)),
            ],
        ),
    ]
