# Generated by Django 4.1.2 on 2022-10-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cases',
            new_name='Case',
        ),
    ]
