# Generated by Django 4.1.2 on 2021-07-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0002_rename_cases_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='level_needy',
            new_name='children',
        ),
    ]
